ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=GE
network={
  ssid="cho"
  scan_ssid=1
  key_mgmt=WPA-PSK
  psk=48e9d1e6be188dda4c0c81345ffda5ac8930d481255706bea2409d8ee0cb015d
}
